name: "Tests: MongoDB"

on:
  - pull_request

jobs:
  mongodb:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
    env:
      PHPUNIT_VERSION: "7.5"

    services:
      mongodb:
        image: percona/percona-server-mongodb:3.6
        ports:
          - 27017:27017

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: xdebug, xhprof, mongodb, tideways_xhprof

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress
          composer require --dev phpunit/phpunit:^$PHPUNIT_VERSION

      - name: Install extensions
        run: ./install-extensions.sh

      - name: Run PHPUnit tests
        run: composer test

# vim:ft=yaml:et:ts=2:sw=2
